# Use the official nginx image as the base image
FROM nginx

# Copy your HTML and CSS files to the appropriate directories in the container
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/

# Expose port 80 to the host machine
EXPOSE 80
